# Generated by Django 6.1.1 on 2026-09-10 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryzone_options_deliveryzone_free_over_and_more'),
        ('orders', '0002_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estado', '-created_at'], name='order_estado_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['telefono'], name='order_telefono_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
    ]
