# Generated by Django 6.1.1 on 2026-09-08 03:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['sort_order', 'cost', 'name'], 'verbose_name': 'Zona de delivery', 'verbose_name_plural': 'Zonas de delivery'},
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='free_over',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
